Dealer/Dealer/Controllers/HomeController.cs
using Dealer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Dealer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /*[Authorize]*/
        public IActionResult Admin()
        {
            return View();
        }
    }
}

Dealer/Dealer/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dealer.Models;

namespace Dealer.Controllers
{
    public class MarcasController : Controller
    {
        private readonly DEALERContext _context;

        public MarcasController(DEALERContext context)
        {
            _context = context;
        }

        // GET: Marcas
        public async Task<IActionResult> Index()
        {
              return _context.Marcas != null ? 
                          View(await _context.Marcas.ToListAsync()) :
                          Problem("Entity set 'DEALERContext.Marcas'  is null.");
        }

        // GET: Marcas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Marcas == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .FirstOrDefaultAsync(m => m.IdMarca == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marcas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marcas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMarca,NombreMarca,UrlLogoMarca")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                _context.Add(marca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Marcas == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        // POST: Marcas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMarca,NombreMarca,UrlLogoMarca")] Marca marca)
        {
            if (id != marca.IdMarca)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.IdMarca))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Marcas == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .FirstOrDefaultAsync(m => m.IdMarca == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Marcas == null)
            {
                return Problem("Entity set 'DEALERContext.Marcas'  is null.");
            }
            var marca = await _context.Marcas.FindAsync(id);
            if (marca != null)
            {
                _context.Marcas.Remove(marca);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(int id)
        {
          return (_context.Marcas?.Any(e => e.IdMarca == id)).GetValueOrDefault();
        }
    }
}

Dealer/Dealer/Views/Home/Admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Administrador";
}

<h1 class="page-admin-header_title admin-header-title">Administrar Servicio Oficial</h1>

<div class="page-admin-container">

    <div class="page-admin-colores page-admin-card">
        <h4>Colores</h4>
        <a asp-controller="ColorExteriors" asp-action="Index" class="btn btn-danger">Colores de exterior</a>
        <a asp-controller="ColorInteriors" asp-action="Index" class="btn btn-dark">Colores de interior</a>
    </div>
    <div class="page-admin-servicio_oficial page-admin-card">
        <h4>Servicio oficial</h4>
        <a asp-controller="ServicioOficials" asp-action="Index" class="btn btn-danger">Admin. Servicio Oficial</a>
        <a asp-controller="ServicioOficialVendedores" asp-action="Index" class="btn btn-secondary">Vendedores</a>
        <a asp-controller="ServicioOficialClientes" asp-action="Index" class="btn btn-dark">Clientes</a>
    </div>
    <div class="page-admin-marca_modelo page-admin-card">
        <h4>Marcas y modelos</h4>
        <a asp-controller="Marcas" asp-action="Index" class="btn btn-danger">Admin. Marcas</a>
        <a asp-controller="Modeloes" asp-action="ListModelos" class="btn btn-dark">Admin. Modelos</a>
    </div>
    <div class="page-admin-equipamiento page-admin-card">
        <h4>Equipamiento</h4>
        <a asp-controller="EquipamientoExtras" asp-action="Index" class="btn btn-danger">Admin. Equipamiento extra</a>
        <a asp-controller="EquipamientoSeries" asp-action="Index" class="btn btn-dark">Admin. Equipamiento de serie</a>
    </div>
</div>

Dealer/Dealer/Views/Home/Index.cshtml
@model Dealer.Models.VehiculosStock

@{
    ViewData["Title"] = "Inicio";
}

<div class="Home-Hero">
    <div class="Home-Hero-img">
        <img src="https://assets.porsche.com/do/santodomingo/-/media/Project/DealerWebsites/DominicanRepublic/SantoDomingo/Stage/Home-Page/Dealer/Porsche-Center-DominicanRepublic-Desktop-2.jpg?rev=20dd0ab307914496bef6d5649b0a97b1&w=1920" />
    </div>
    <div class="Home-Hero-img">
        <img src="https://assets.porsche.com/do/santodomingo/-/media/Project/DealerWebsites/DominicanRepublic/SantoDomingo/Stage/Porsche-Approved/Update/PorscheApproved_Slider_Desk_ESP.jpg?rev=0ab55db1a8d9408aa679a975c67d2ede&w=1920" />
    </div>
    <div class="Home-Hero-img">
        <img src="https://assets.porsche.com/do/santodomingo/-/media/Project/DealerWebsites/DominicanRepublic/SantoDomingo/Stage/Garantia-Extendida-Porsche-Approved/Update-01-23/Garantia_Extendida_Slider_Desk.jpg?rev=bdee8d0100204722932d69dd855161e0&w=1920" />
    </div>
    <div class="Home-Hero-img">
        <img src="https://assets.porsche.com/do/santodomingo/-/media/Project/DealerWebsites/DominicanRepublic/SantoDomingo/Stage/Porsche-Approved/Update/PorscheApproved_Slider_Desk_ESP.jpg?rev=0ab55db1a8d9408aa679a975c67d2ede&w=1920" />
    </div>

</div>



<div class="Home-banners">

    <h2 class="home-headers">Nuestros vehículos</h2>

    <div class="Home-banners-container">
        <div class="Home-banners-content banner-content-1">
            <a asp-controller="VehiculosStocks" asp-action="Index">
                <span><i class="fa-solid fa-chevron-up" style="color: #ffffff;"></i>Vehículos nuevos</span>
            </a>
        </div>
        <div class="Home-banners-content banner-content-2">
            <a asp-controller="VehiculosStocks" asp-action="Index">
                <span><i class="fa-solid fa-chevron-up" style="color: #ffffff;"></i>Vehículos de reestreno</span>
            </a>
        </div>
    </div>

</div>

<div class="Home-build">
    <h2 class="home-headers">Diseña tu Porsche</h2>

    <div class="Home-build-content">
        <div class="Home-build-imgContainer">
            <img src="https://assets-v2.porsche.com/-/media/Project/PCOM/SharedSite/PorscheExclusiveManufaktur/Personality/001-hero-13-5-intro.jpg?rev=d5a0408d1e944d21af3dcf4490e1e9de&w=1299" />
        </div>

        <div class="Home-build-Caption">
            <h4>Un Porsche a tu estilo!</h4>

            <p class="Home-build-Caption-text"><i class="fa-solid fa-circle fa-2xs" style="margin-right:5px;"></i>Haz que uno de nuestros modelos se parezca a ti!</p>
            <p class="Home-build-Caption-text"><i class="fa-solid fa-circle fa-2xs" style="margin-right:5px;"></i>Personaliza con una inmesa paleta de colores.</p>
            <p class="Home-build-Caption-text"><i class="fa-solid fa-circle fa-2xs" style="margin-right:5px;"></i>Crea tu propia experiencia Porsche.</p>

            <div class="Home-build-imgContainer-configuratorBtn">
                <i class='bx bx-cog'></i>
                <a asp-controller="Modeloes" asp-action="Index">Ir al configurador</a>
            </div>
        </div>
    </div>

</div>

<div class="Home-testDrive">
    <h4 class="home-headers">Solicita una prueba de manejo</h4>

    <form>
        <div class="form-group">
            <label class="control-label">Modelo*</label>
            <select class="form-control form-select" asp-items="ViewBag.IdModelo" required></select>
        </div>
        <div class="form-group">
            <div>
                <label class="control-label">Fecha de preferencia*</label>
                <input class="form-control" type="date" style="width:15rem;" required />
            </div>

            <div>
                <label class="control-label">Hora de preferencia*</label>
                <input class="form-control" type="time" style="width:15rem;" required />
            </div>

        </div>

        <h5>Tus datos</h5>

        <div class="form-group">
            <label class="control-label">Título*</label>
            <select class="form-control form-select" required>
                <option></option>
                <option>Sr.</option>
                <option>Sra.</option>
                <option>Srita.</option>
                <option>Dr.</option>
                <option>Lic.</option>
                <option>Ing.</option>
            </select>
        </div>

        <div class="form-group">
            <label class="control-label">Nombre/s*</label>
            <input class="form-control" type="text" autocomplete="on" required />
        </div>

        <div class="form-group">
            <label class="control-label">Apellido/s*</label>
            <input class="form-control" type="text" autocomplete="on" required />
        </div>

        <div class="form-group">
            <label class="control-label">Correo electrónico*</label>
            <input class="form-control" type="email" autocomplete="on" required />
        </div>

        <div class="form-group">
            <label class="control-label">Télefono</label>
            <input class="form-control" type="tel" autocomplete="on" />
        </div>

        <div class="form-group">
            <label class="control-label">Método de contacto preferido</label>
            <select class="form-control form-select">
                <option>Teléfono</option>
                <option>Correo electrónico</option>
            </select>
        </div>

        <div class="form-group">
            <label class="control-label">Mensaje</label>
            <textarea rows="4" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <input class="form-check-input" type="checkbox" required />
            <label class="form-check-label">Acepto los términos y condiciones*</label>
        </div>

        <p>
            <span>*Test Drive sujeto a disponibilidad previa coordinación y confirmación con un ejecutivo comercial.</span>

            <div class="form-group">
                <input type="submit" class="btn btn-danger" value="Enviar" />
            </div>
    </form>
</div>

<div class="Home-contact" id="Home-contact">
    <h4 class="home-headers">Dirección y contacto</h4>
    <div class="Home-contact-content">
        <div class="Home-contact-maps">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d6617.159139079841!2d-69.90952976569588!3d18.475135524339077!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2sdo!4v1680483621782!5m2!1ses!2sdo" width="900" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

        <div class="Home-contact-contacts">
            <h6>Contacto:</h6>
            <p><i class='bx bx-map'></i>Av. Máximo Gómez 72, Santo Domingo 10100</p>
            <p><i class='bx bx-phone'></i>+809-699-6525</p>
            <p><i class='bx bx-phone'></i>Customer Interaction Center +1849-414-5929</p>
            <div><i class='bx bx-envelope'></i><a href="mailto:soporteclientes@porsche.com">soporteclientes@porsche.com</a></div>
        </div>
    </div>
</div>
<footer class="Home-footer">

    <p class="Home-footer-copy"> &copy; @DateTime.Now.Year Porsche IDK3M </p>

    <div class="Home-footer-social">
        <a><i class='bx bxl-facebook-square bx-md'></i></a>
        <a><i class='bx bxl-instagram bx-md'></i></a>
        <a><i class='bx bxl-youtube bx-md'></i></a>
    </div>
</footer>