Dealer/Dealer/Models/VehiculosStock.cs
using System;
using System.Collections.Generic;
using Dealer.Models;

namespace Dealer.Models
{
    public partial class VehiculosStock
    {
        public VehiculosStock()
        {
            VentaPrecioVehiculoStockNavigations = new HashSet<Venta>();
            VentaVinVehiculoStockNavigations = new HashSet<Venta>();
        }

        public int IdVehiculoStock { get; set; }
        public int? IdMarca { get; set; }
        public int? IdModelo { get; set; }
        public string? Vin { get; set; }
        public int? ColorExterior { get; set; }
        public int? ColorInterior { get; set; }
        public string? Anio { get; set; }
        public string? DescripcionEquipamientoExtra { get; set; }
        public decimal? Precio { get; set; }
        public string? Img { get; set; }
        public int? Condicion { get; set; }
        public string? Img2 { get; set; }
        public string? Img3 { get; set; }
        public string? Img4 { get; set; }
        public string? Img5 { get; set; }
        public string? Img6 { get; set; }
        public string? Img7 { get; set; }

        public virtual ColorExterior? ColorExteriorNavigation { get; set; }
        public virtual ColorInterior? ColorInteriorNavigation { get; set; }
        public virtual CondicionVehiculo? CondicionNavigation { get; set; }
        public virtual Marca? IdMarcaNavigation { get; set; }
        public virtual Modelo? IdModeloNavigation { get; set; }
        public virtual ICollection<Venta> VentaPrecioVehiculoStockNavigations { get; set; }
        public virtual ICollection<Venta> VentaVinVehiculoStockNavigations { get; set; }
    }
}

Dealer/Dealer/Controllers/VehiculosStocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dealer.Models;
using System.Numerics;

namespace Dealer.Controllers
{
    public class VehiculosStocksController : Controller
    {
        private readonly DEALERContext _context;

        public VehiculosStocksController(DEALERContext context)
        {
            _context = context;
        }

        // GET: VehiculosStocks
        public async Task<IActionResult> Index(int? condicion, int? modelo, string? anio)
        {
            var dEALERContext = from VehiculosStock in _context.VehiculosStocks select VehiculosStock;

            dEALERContext = _context.VehiculosStocks
            .Include(v => v.ColorExteriorNavigation)
            .Include(v => v.ColorInteriorNavigation)
            .Include(v => v.CondicionNavigation)
            .Include(v => v.IdMarcaNavigation)
            .Include(v => v.IdModeloNavigation);

            ViewData["IdModelo"] = new SelectList(_context.Modelos, "IdModelo", "NombreModelo");
            ViewData["Condicion"] = new SelectList(_context.CondicionVehiculos, "IdCondicion", "Condicion");

            if (modelo != null)
            {
                dEALERContext = dEALERContext.Where(v => v.IdModelo == modelo);
            } 

            if (condicion != null)
            {
                dEALERContext = dEALERContext.Where(v => v.Condicion == condicion);
            }

            if (anio != null)
            {
                dEALERContext = dEALERContext.Where(v => v.Anio == anio);
            }



            return View(await dEALERContext.ToListAsync());
        }

        // GET: VehiculosStocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VehiculosStocks == null)
            {
                return NotFound();
            }

            var vehiculosStock = await _context.VehiculosStocks
                .Include(v => v.ColorExteriorNavigation)
                .Include(v => v.ColorInteriorNavigation)
                .Include(v => v.CondicionNavigation)
                .Include(v => v.IdMarcaNavigation)
                .Include(v => v.IdModeloNavigation)
                .FirstOrDefaultAsync(m => m.IdVehiculoStock == id);

            if (vehiculosStock == null)
            {
                return NotFound();
            }

            var equipamientoSerie = _context.EquipamientoSeries
            .Where(es => es.IdModelo == vehiculosStock.IdModelo)
            .ToList();

            ViewBag.EquipamientoSerie = equipamientoSerie;

            return View(vehiculosStock);
        }

        // GET: VehiculosStocks/Create
        public IActionResult Create()
        {
            ViewData["ColorExterior"] = new SelectList(_context.ColorExteriors, "IdColorExterior", "ColorExterior1");
            ViewData["ColorInterior"] = new SelectList(_context.ColorInteriors, "IdColorInterior", "ColorInterior1");
            ViewData["Condicion"] = new SelectList(_context.CondicionVehiculos, "IdCondicion", "Condicion");
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "NombreMarca");
            ViewData["IdModelo"] = new SelectList(_context.Modelos, "IdModelo", "NombreModelo");
            return View();
        }

        // POST: VehiculosStocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVehiculoStock,IdMarca,IdModelo,Vin,ColorExterior,ColorInterior,Anio,DescripcionEquipamientoExtra,Precio,Img,Condicion,Img2,Img3,Img4,Img5,Img6,Img7")] VehiculosStock vehiculosStock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehiculosStock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ColorExterior"] = new SelectList(_context.ColorExteriors, "IdColorExterior", "IdColorExterior", vehiculosStock.ColorExterior);
            ViewData["ColorInterior"] = new SelectList(_context.ColorInteriors, "IdColorInterior", "IdColorInterior", vehiculosStock.ColorInterior);
            ViewData["Condicion"] = new SelectList(_context.CondicionVehiculos, "IdCondicion", "IdCondicion", vehiculosStock.Condicion);
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "IdMarca", vehiculosStock.IdMarca);
            ViewData["IdModelo"] = new SelectList(_context.Modelos, "IdModelo", "IdModelo", vehiculosStock.IdModelo);
            return View(vehiculosStock);
        }

        // GET: VehiculosStocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VehiculosStocks == null)
            {
                return NotFound();
            }

            var vehiculosStock = await _context.VehiculosStocks.FindAsync(id);
            if (vehiculosStock == null)
            {
                return NotFound();
            }
            ViewData["ColorExterior"] = new SelectList(_context.ColorExteriors, "IdColorExterior", "ColorExterior1", vehiculosStock.ColorExterior);
            ViewData["ColorInterior"] = new SelectList(_context.ColorInteriors, "IdColorInterior", "ColorInterior1", vehiculosStock.ColorInterior);
            ViewData["Condicion"] = new SelectList(_context.CondicionVehiculos, "IdCondicion", "Condicion", vehiculosStock.Condicion);
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "NombreMarca", vehiculosStock.IdMarca);
            ViewData["IdModelo"] = new SelectList(_context.Modelos, "IdModelo", "NombreModelo", vehiculosStock.IdModelo);
            return View(vehiculosStock);
        }

        // POST: VehiculosStocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVehiculoStock,IdMarca,IdModelo,Vin,ColorExterior,ColorInterior,Anio,DescripcionEquipamientoExtra,Precio,Img,Condicion,Img2,Img3,Img4,Img5,Img6,Img7")] VehiculosStock vehiculosStock)
        {
            if (id != vehiculosStock.IdVehiculoStock)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehiculosStock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculosStockExists(vehiculosStock.IdVehiculoStock))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ColorExterior"] = new SelectList(_context.ColorExteriors, "IdColorExterior", "IdColorExterior", vehiculosStock.ColorExterior);
            ViewData["ColorInterior"] = new SelectList(_context.ColorInteriors, "IdColorInterior", "IdColorInterior", vehiculosStock.ColorInterior);
            ViewData["Condicion"] = new SelectList(_context.CondicionVehiculos, "IdCondicion", "IdCondicion", vehiculosStock.Condicion);
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "IdMarca", vehiculosStock.IdMarca);
            ViewData["IdModelo"] = new SelectList(_context.Modelos, "IdModelo", "IdModelo", vehiculosStock.IdModelo);
            return View(vehiculosStock);
        }

        // GET: VehiculosStocks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VehiculosStocks == null)
            {
                return NotFound();
            }

            var vehiculosStock = await _context.VehiculosStocks
                .Include(v => v.ColorExteriorNavigation)
                .Include(v => v.ColorInteriorNavigation)
                .Include(v => v.CondicionNavigation)
                .Include(v => v.IdMarcaNavigation)
                .Include(v => v.IdModeloNavigation)
                .FirstOrDefaultAsync(m => m.IdVehiculoStock == id);
            if (vehiculosStock == null)
            {
                return NotFound();
            }

            return View(vehiculosStock);
        }

        // POST: VehiculosStocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VehiculosStocks == null)
            {
                return Problem("Entity set 'DEALERContext.VehiculosStocks'  is null.");
            }
            var vehiculosStock = await _context.VehiculosStocks.FindAsync(id);
            if (vehiculosStock != null)
            {
                _context.VehiculosStocks.Remove(vehiculosStock);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculosStockExists(int id)
        {
            return (_context.VehiculosStocks?.Any(e => e.IdVehiculoStock == id)).GetValueOrDefault();
        }
    }
}

Dealer/Dealer/Views/VehiculosStocks/Create.cshtml
@model Dealer.Models.VehiculosStock

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>VehiculosStock</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdMarca" class="control-label"></label>
                <select asp-for="IdMarca" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" asp-items="ViewBag.IdMarca"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdModelo" class="control-label"></label>
                <select asp-for="IdModelo" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" asp-items="ViewBag.IdModelo"></select>
            </div>
            <div class="form-group">
                <label asp-for="Vin" class="control-label"></label>
                <input asp-for="Vin" class="form-control create-input" maxlength="17"/>
                <span asp-validation-for="Vin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ColorExterior" class="control-label"></label>
                <select asp-for="ColorExterior" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" asp-items="ViewBag.ColorExterior"></select>
            </div>
            <div class="form-group">
                <label asp-for="ColorInterior" class="control-label"></label>
                <select asp-for="ColorInterior" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" asp-items="ViewBag.ColorInterior"></select>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control create-input" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionEquipamientoExtra" class="control-label"></label>
                <textarea asp-for="DescripcionEquipamientoExtra" class="form-control create-input" rows="4"></textarea>
                <span asp-validation-for="DescripcionEquipamientoExtra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control create-input" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input asp-for="Img" class="form-control create-input" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condicion" class="control-label"></label>
                <select asp-for="Condicion" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" asp-items="ViewBag.Condicion"></select>
            </div>
            <div class="form-group">
                <label asp-for="Img2" class="control-label"></label>
                <input asp-for="Img2" class="form-control" />
                <span asp-validation-for="Img2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img3" class="control-label"></label>
                <input asp-for="Img3" class="form-control" />
                <span asp-validation-for="Img3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img4" class="control-label"></label>
                <input asp-for="Img4" class="form-control" />
                <span asp-validation-for="Img4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img5" class="control-label"></label>
                <input asp-for="Img5" class="form-control" />
                <span asp-validation-for="Img5" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img6" class="control-label"></label>
                <input asp-for="Img6" class="form-control" />
                <span asp-validation-for="Img6" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img7" class="control-label"></label>
                <input asp-for="Img7" class="form-control" />
                <span asp-validation-for="Img7" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dealer/Dealer/Views/VehiculosStocks/Delete.cshtml
@model Dealer.Models.VehiculosStock

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehiculosStock</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionEquipamientoExtra)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescripcionEquipamientoExtra)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img3)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img3)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img4)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img5)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img5)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img6)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img6)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Img7)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Img7)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ColorExteriorNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ColorExteriorNavigation.IdColorExterior)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ColorInteriorNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ColorInteriorNavigation.IdColorInterior)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CondicionNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CondicionNavigation.IdCondicion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdMarcaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdMarcaNavigation.IdMarca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdModeloNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdModeloNavigation.IdModelo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdVehiculoStock" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Dealer/Dealer/Views/VehiculosStocks/Details.cshtml
@model Dealer.Models.VehiculosStock

@{
    ViewData["Title"] = "Detalles";
}

<div class="details-car_inv-container">

    <div class="details-car_inv-title_price-container">
        <h1> @Html.DisplayFor(model => model.IdMarcaNavigation.NombreMarca) @Html.DisplayFor(model => model.IdModeloNavigation.NombreModelo)  @Html.DisplayFor(model => model.Anio)</h1>
        <p class="details-car_inv-price">
            @((Model.Precio.HasValue ? "US$ " + Model.Precio.Value.ToString("N2") : ""))
        </p>
    </div>
    <hr />
    <div class="details-car_inv_showCarData">

        <div class="details-car_inv-img-container">
            <img src="@Html.DisplayFor(model => model.Img)" />
            <img src="@Html.DisplayFor(model => model.Img2)" />
            <img src="@Html.DisplayFor(model => model.Img3)" />
            <img src="@Html.DisplayFor(model => model.Img4)" />
            <img src="@Html.DisplayFor(model => model.Img5)" />
            <img src="@Html.DisplayFor(model => model.Img6)" />
            <img src="@Html.DisplayFor(model => model.Img7)" />
        </div>

        <div class="details-car_inv-info">

            <div class="details-car_inv-generalData">

                <div class="details-car_inv-title_btnShop">
                    <h4>Datos Generales</h4>
                    <a class="btn btn-danger">Comprar</a>
                </div>

                <table class="table">
                    <tbody>
                        <tr>
                            <td colspan="2"></td>
                        </tr>
                        <tr>
                            <td><span>VIN:</span></td>
                            <td colspan="1">@Html.DisplayFor(model => model.Vin)</td>
                        </tr>
                        <tr>
                            <td><span>Precio:</span></td>
                            <td colspan="1"> @((Model.Precio.HasValue ? "US$ " + Model.Precio.Value.ToString("N2") : ""))</td>
                        </tr>
                        <tr>
                            <td><span>Motor:</span></td>
                            @if (Model.IdModeloNavigation.NombreModelo.Contains("Taycan"))
                            {
                                <td>Eléctrico</td>
                            }
                            else
                            {
                                <td colspan="1">@Html.DisplayFor(model => model.IdModeloNavigation.Cilindrada) cilindros</td>
                            }

                        </tr>
                        <tr>
                            <td><span>Potencia:</span></td>
                            <td>@Html.DisplayFor(model => model.IdModeloNavigation.Potencia) HP</td>
                        </tr>
                        <tr>
                            <td><span>Color Exterior:</span></td>
                            <td colspan="1">@Html.DisplayFor(model => model.ColorExteriorNavigation.ColorExterior1)</td>
                        </tr>
                        <tr>
                            <td><span>Color Interior:</span></td>
                            <td colspan="1">@Html.DisplayFor(model => model.ColorInteriorNavigation.ColorInterior1)</td>
                        </tr>
                        <tr>
                            <td><span>Tracción:</span></td>
                            <td colspan="1">@Html.DisplayFor(model => model.IdModeloNavigation.Traccion)</td>
                        </tr>
                        <tr>
                            <td><span>Transmisión:</span></td>
                            @if (Model.IdModeloNavigation.NombreModelo.Contains("GT3") || Model.IdModeloNavigation.NombreModelo.Contains("GT4") || Model.IdModeloNavigation.NombreModelo.Contains("911 Sport Classic II"))
                            {
                                <td colspan="1">Manual</td>
                            }
                            else
                            {
                                <td colspan="1">Automática PDK</td>
                            }
                        </tr>
                        <tr>
                            <td><span>Combustible:</span></td>
                            <td colspan="1"> @Html.DisplayFor(model => model.IdModeloNavigation.Combustible)</td>
                        </tr>
                        <tr>
                            <td><span>Pasajeros:</span></td>
                            <td colspan="1">@Html.DisplayFor(model => model.IdModeloNavigation.Pasajeros)</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="details-car_inv-equipamiento_Base">
                <h4>Equipamiento</h4>

                <ul>
                    @foreach (var item in ViewBag.EquipamientoSerie)
                    {
                        <li>@item.NombreEquipamientoExtra</li>
                    }
                </ul>

            </div>

            <div class="details-car_inv-equipamiento_Extra">
                <h4>Extras</h4>
                @Html.DisplayFor(model => model.DescripcionEquipamientoExtra)
            </div>
        </div>
    </div>
</div>

Dealer/Dealer/Views/VehiculosStocks/Index.cshtml
@model IEnumerable<Dealer.Models.VehiculosStock>

@{
    ViewData["Title"] = "Inventario de vehiculos";
}

<h1 class="methods-headers">@ViewData["Title"]</h1>

<div class="inventario-vehiculo">

    <div class="inventario-vehiculo-filtro">

        <form asp-controller="VehiculosStocks" asp-action="Index" class="form-filtro-car_inv">

            <h3>Filtro</h3>
            <hr />

            <div class="form-group">
                <label class="control-label">Modelo</label><br />
                <select name="modelo" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" onchange="submit()" asp-items="ViewBag.IdModelo">
                <option>Seleccione</option>
                </select>
            </div>

            <div class="form-group">
                <label class="control-label">Condición</label>
                <select name="condicion" class="form-control create-input js-example-placeholder-single js-example-basic-single js-states" onchange="submit()" asp-items="ViewBag.Condicion">
                <option>Seleccione</option>
                </select>
            </div>
            <hr />
        </form>

    </div>

    @if (Model.Any())
    {
        <div class="inventario-vehiculo-container">

            @foreach (var item in Model)
            {
                <div class="inventario-vehiculo-card">
                    <div class="inventario-vehiculo-img">
                        <a asp-action="Details" asp-route-id="@item.IdVehiculoStock">
                            <img src="@Html.DisplayFor(modelItem => item.Img)" />
                        </a>
                    </div>
                    @*<div class="inventario-vehiculo-precio"></div>*@
                    <div class="inventario-vehiculo-marca_modelo">
                        <span> @Html.DisplayFor(modelItem => item.IdMarcaNavigation.NombreMarca) @Html.DisplayFor(modelItem => item.IdModeloNavigation.NombreModelo)</span>
                    </div>
                    <div class="inventario-vehiculo-anio_condicion">
                        <span> @Html.DisplayFor(modelItem => item.Anio) - @Html.DisplayFor(modelItem => item.CondicionNavigation.Condicion)</span>
                    </div>

                </div>

            }
        </div>
    }
    else
    {
        <div class="inventario-vehiculo-results_not_found">
            <p>No se encontraron resultados🔍</p>
        </div>
    }

</div>